version = 3

[Gemma-4-E4B-it]
;repo = unsloth/Gemma-4-E4B-it-GGUF
model = /root/.cache/huggingface/hub/gemma-4-E4B-it-Q4_K_M.gguf
ngl = 99
ctx-size = 32768
fa = on
jinja = on

[Gemma-4-31B-it]
;repo = unsloth/gemma-4-31B-it-GGUF
model = gemma-4-31B-it-Q6_K.gguf 
ngl = 99
ctx-size = 32768
fa = on
jinja = on

[Qwen3.6-27B]
;repo = unsloth/Qwen3.6-27B-GGUF
model = Qwen3.6-27B-Q5_K_M.gguf
ngl = 99
ctx-size = 262144
fa = on
jinja = on

