version = 2

[Gemma-4-E4B-it]
;repo = unsloth/Gemma-4-E4B-it-GGUF
model = gemma-4-E4B-it-Q4_K_M.gguf
ngl = 99
ctx-size = 32768
temp = 0.6
top-p = 0.9
fa = on
jinja = on

[Gemma-4-31B-it]
;repo = unsloth/gemma-4-31B-it-GGUF
model = gemma-4-31B-it-Q6_K.gguf 
ngl = 0
ctx-size = 131072
temp = 0.4
top-p = 0.9
fa = on
jinja = on
chat-template = chatml

[Qwen3.6-27B]
;repo = unsloth/Qwen3.6-27B-GGUF
model = Qwen3.6-27B-Q5_K_M.gguf
ngl = 0
ctx-size = 262144
temp = 0.5
top-p = 0.85
fa = on
jinja = on

