FROM registry.fedoraproject.org/fedora-toolbox:44 
RUN dnf --assumeyes install pip yq && dnf clean all && rm -rf /var/cache/dnf/*
RUN pip install huggingface_hub
COPY files/hf-download.sh /usr/local/bin/
CMD ["/usr/local/bin/hf-download.sh"]
